[package]
name = "picross"
version = "0.1.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2018"

[dependencies]
ggez = "0.5"
nalgebra = "0.18.0"
rand = "0.6"
serde = "1.0"
ron = { git = "https://github.com/ron-rs/ron.git" }
